completed issue-4-delete-an-entry - Fredrick Rana
fredrickrana/code-journal pull request #8
Opened 2022-07-20 23:38 UTC by fredrickrana

![Kapture 2022-07-20 at 16 30 13](https://user-images.githubusercontent.com/103611252/180099822-ded3cf65-c5b6-4c3f-91c6-3773a04d8b91.gif)
![Kapture 2022-07-20 at 16 32 31](https://user-images.githubusercontent.com/103611252/180100063-2ae3636b-3090-45f7-92da-eefd1b7a705a.gif)
![Kapture 2022-07-20 at 16 34 19](https://user-images.githubusercontent.com/103611252/180100185-6e706303-b036-4e82-9dde-72299b4c26c8.gif)
![Kapture 2022-07-20 at 16 37 46](https://user-images.githubusercontent.com/103611252/180100500-2134827b-4f97-48d8-bded-16f0244d22d3.gif)

2022-07-20 23:43 UTC, codingcodymiller requested changes

2022-07-20 23:43 UTC, codingcodymiller commented on js/main.js
> +    data.nextEntryId = data.entries.length + 1;
This is incorrect, you shouldn't be using the length of the array to make the next entry, you should be using `data.nextEntryId`

2022-07-20 23:43 UTC, codingcodymiller commented on js/main.js
> +      deleteInDataEntries();
Do you ever clear the form or set `data.editing` back to `null` after this? What happens if you go to make a new entry after deleting an entry, is the old data still there?

2022-07-21 00:10 UTC, fredrickrana commented
![Kapture 2022-07-20 at 17 00 26](https://user-images.githubusercontent.com/103611252/180102592-5870f97f-3559-4ea7-a934-541674acab41.gif)
![Kapture 2022-07-20 at 17 09 20](https://user-images.githubusercontent.com/103611252/180103238-bd8af365-1614-4964-ba61-0e3498b83533.gif)

2022-07-21 00:15 UTC, codingcodymiller approved these changes

2022-07-21 00:17 UTC, merged